oscillatingSphereInCube/base/Allrun: Add instructions for generating unstructured hex mesh (`CARTESIAN`)

diff --git a/oscillatingSphereInCube/base/Allrun b/oscillatingSphereInCube/base/Allrun
--- a/oscillatingSphereInCube/base/Allrun
+++ b/oscillatingSphereInCube/base/Allrun
@@ -14,9 +14,10 @@
 #     Mesh type:
 #         HEX           structured hexagonal mesh
 #         HEX_GRADED    structured hexagonal graded mesh
+#         CARTESIAN     unstructured hexagonal mesh
 #         TET           unstructured tetrahedral mesh
 #         POLY          unstructured polyhedral mesh
-:     "${MESH:=HEX}"
+:     "${MESH:=CARTESIAN}"
 #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
 cd "${0%/*}" || exit    # Run from this directory
 set -e
@@ -53,6 +54,31 @@ case "${MESH}" in
             # The following command is run twice to reduce "point displacement
             # motion" down to zero. For more information, please take a look at
             # the output of this command and/or its help using the `-help` flag.
+            runApplication -suffix '1' projectPatchToSphere sphere '(0 0 0)' 0.5
+            runApplication -suffix '2' projectPatchToSphere sphere '(0 0 0)' 0.5
+        fi
+        ;;
+
+    "CARTESIAN")
+        if ! command -v cartesianMesh &> /dev/null
+        then
+            echo "Cartesianmesh not found. Please install it."
+        fi
+
+        # Combine surfaces into one surface
+        cat ./boundingBox.stl ./sphere.stl > geometry.stl
+
+        # Convert the surface from STL to FMS format
+        runApplication surfaceToFMS geometry.stl
+
+        # Generate the mesh using cfMesh
+        MESH_LEVEL="${MESH_LEVEL}" runApplication cartesianMesh
+
+        if ! command -v projectSphereToPatch &> /dev/null
+        then
+            printf "%s %s\n" \
+                   "Projecting the 'sphere' patch onto a sphere" \
+                   "of radius 5 whose centre is located at '(0 0 0)'"
             runApplication -suffix '1' projectPatchToSphere sphere '(0 0 0)' 0.5
             runApplication -suffix '2' projectPatchToSphere sphere '(0 0 0)' 0.5
         fi
